---

- name: Install iptables
  apt: name={{ item }} state=present
  with_items:
    - ipset
    - iptables-persistent

- name: Prepare fw
  shell:
    cmd: | 
      {{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/apply_iptables_patch.sh;
      {{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/firewall.sh --reset;
      {{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/firewall.sh --lm;
  args:
    executable: /bin/bash
  tags:
    - prepare-fw

- name: Setup fw ipsets
  block:
    - include: "setup_ipset.yml"
 
- name: Setup FW (basic setup, add LAN-001)
  shell: '{{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/firewall.sh \ 
--wan int={{ wan_i }} sn={{ wan_sn }} ip={{ wan_ip }} \
wan_out_tcp_ports="{{ WAN001_OUT_TCP_PORTSET }}" \
wan_out_udp_ports="{{ WAN001_OUT_UDP_PORTSET }}" \
trusted="{{ WAN001_TRUSTED_IN_FW_IPSET }}" \
wan_in_tcp_ports="{{ WAN001_IN_FW_TCP_PORTSET }}" \
wan_in_udp_ports="{{ WAN001_IN_FW_UDP_PORTSET }}" \                                                 
synproxy \
--lan int={{ lan001_i }} sn={{ lan001_sn }} ip={{ lan001_ip }} \
out_tcp_fwr_ports={{ LAN001_OUT_FWR_TCP_PORTSET }} out_udp_fwr_ports={{ LAN001_OUT_FWR_UDP_PORTSET }} \
trusted="{{ LAN001_TRUSTED_IN_FW_IPSET }}" \
in_tcp_fw_ports="{{ LAN001_IN_FW_TCP_PORTSET }}"
in_udp_fw_ports="{{ LAN001_IN_FW_UDP_PORTSET }}"'
  register: basicSetupOutput_Reg
  tags:
    - setup-fw

- name: Port forward to LAN001
  shell:  
    cmd: |
      {{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/firewall.sh --pf wan_iface={{ wan_i }} \
      from_port={{ LAN001_PF_FROM_PORT }} to_ip={{ LAN001_PF_TO_IP }} to_port={{ LAN001_PF_TO_PORT }}
  args:
    executable: /bin/bash
  tags:
    - pf-fw

- name: Add LAN002
  shell: '{{ rollUpIt_lnx_dst }}/rollUpIt.lnx/libs/lnx_debian09/iptables/utils/firewall.sh --lan int={{ lan002_i }} sn={{ lan002_sn }} \
ip={{ lan002_ip }} \
out_tcp_fwr_ports={{ LAN002_OUT_FWR_TCP_PORTSET }} out_udp_fwr_ports={{ LAN002_OUT_FWR_UDP_PORTSET }} \
wan_int={{ wan_i }} \
trusted="{{ LAN002_TRUSTED_IN_FW_IPSET }}" \
in_tcp_fw_ports="{{ LAN002_IN_FW_TCP_PORTSET }}"
in_udp_fw_ports="{{ LAN002_IN_FW_UDP_PORTSET }}"'
  tags:
    - add-lan002
