---
- name: Ensure group "develop,adm" exists
  group:
    name: "{{ item.name}}"
    state: present
  with_items:
    - {
      name: "develop"
    }
    - {
      name: "adm"
    }

    #- name: Get updated rollUpIt.git
    #  local_action: 
    #      module: git
    #      repo: https://github.com/{{ githubuser | urlencode }}/rollUpIt.lnx.git
    #      version: develop
    #      dest: "files"
    #  become: False
    #  run_once: True
- name: Update local RUI
  local_action: shell rm -Rf files/rollUpIt.lnx; cd files; 
                      wget -r -nv -nH --cut-dir 1 ftp://ftp_user:SUPER@172.17.0.132/pub/rollUpIt.lnx;
                      chown -Rf likhobabin_im:likhobabin_im ../rollUpIt.lnx;
                      find . -iname "*.sh" -exec chmod 775 {} \;
  become: False
  run_once: True

# Basic srv preparation
- name: Create admin user
  user:
    name: "{{ admin_user }}"
    shell: /bin/bash
    groups: "{{ admin_groups }}" 
    append: yes
    # use S..R
    password: "{{ admin_password }}"

- name: Pass ssh id_pub keys
  # set to ‘true’/’yes’ to activate privilege escalation.
  become: false
  local_action: shell cat $HOME/.ssh/id_rsa.pub | ssh "{{ vagrant_user }}"@"{{ ansible_eth1['ipv4']['address'] }}" 'sudo -u {{ admin_user }} mkdir -m 700 -p /home/"{{ admin_user }}"/.ssh; sudo -u {{ admin_user}} tee -a /home/"{{ admin_user }}"/.ssh/authorized_keys; sudo chmod 600 /home/"{{ admin_user }}"/.ssh/authorized_keys'

- name: Add sudoers admin group file
  template:
    src: sudo_admgr_add.j2
    dest: /etc/sudoers.d/local_admgr_add
    force: no
    owner: root
    group: root
    mode: 440

- name: Setup sudoers and sshd_config 
  replace:
    path: "{{ item.path }}"
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - {
        path: "/etc/sudoers",
        regexp: '^#[^\S\n\t]*(#includedir)[^\S\n\t]*(/etc/sudoers\.d)\s*$',
        replace: '\1 \2'
      }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '#(PermitRootLogin).*$',
      replace: '\1 no'
    }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '^#PubkeyAuthentication.*$',
      replace: 'PubkeyAuthentication yes'
    }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '^#PasswordAuthentication.*$',
      replace: 'PasswordAuthentication yes'
    }
  notify: restart sshd

- name: Setup logging
  block:
    - include: "setup_logging.yml"
      #  rescue:
      #    - debug:
      #        msg: 'Error: Failed to setup logging'
  
- name: Prepare script dir
  file:
    path: "{{ rollUpIt_lnx_dst }}"
    state: directory
    owner: root
    group: develop
    mode: '0775'

- name: Update RUI
  shell: 'rm -Rf rollUpIt.lnx 2>/dev/null;
          wget -r -nv -nH --cut-dir 1 ftp://ftp_user:SUPER@172.17.0.132/pub/rollUpIt.lnx;
          chown -Rf root:develop {{ rollUpIt_lnx_dst }}/rollUpIt.lnx;
          find {{ rollUpIt_lnx_dst }}/rollUpIt.lnx -iname "*.sh" -exec chmod 775 {} \;'
  args:
    chdir: "{{ rollUpIt_lnx_dst }}"
  tags: update-rui 

- name: Basic setup
  shell: '{{ rollUpIt_lnx_dst }}/rollUpIt.lnx/tests/base/test_ansibleBasicSetup.sh {{ admin_user }}'
  register: basicSetupOutput_Reg

- debug: var=basicSetupOutput_Reg
