---
- name: Ensure group "develop" exists
  group:
    name: develop
    state: present

# Basic srv preparation
- name: Create admin user
  user:
    name: "{{ admin_user }}"
    shell: /bin/bash
    groups: "{{ admin_groups }}" 
    append: yes
    # use S..R
    password: "{{ admin_password }}"

- name: Pass ssh id_pub keys
  # set to ‘true’/’yes’ to activate privilege escalation.
  become: false
  local_action: shell cat $HOME/.ssh/id_rsa.pub | ssh "{{ vagrant_user }}"@"{{ ansible_eth1['ipv4']['address'] }}" 'sudo -u {{ admin_user }} mkdir -m 700 -p /home/"{{ admin_user }}"/.ssh; sudo -u {{ admin_user}} tee -a /home/"{{ admin_user }}"/.ssh/authorized_keys; sudo chmod 600 /home/"{{ admin_user }}"/.ssh/authorized_keys'

  #- name: Add sudoers admin group file
  #  template:
  #    src: sudo_admgr_add.j2
  #    dest: /etc/sudoers.d/local_admgr_add
  #    owner: root
  #    group: root
  #    mode: 440

- name: Setup sudoers and sshd_config 
  replace:
    path: "{{ item.path }}"
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    #    - {
    #      path: "/etc/sudoers",
    #      regexp: '^#[^\S\n\t]*(#includedir)[^\S\n\t]*(/etc/sudoers\.d)\s*$',
    #      replace: '\1 \2'
    #    }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '#(PermitRootLogin).*$',
      replace: '\1 no'
    }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '^#PubkeyAuthentication.*$',
      replace: 'PubkeyAuthentication yes'
    }
    - {
      path: "/etc/ssh/sshd_config",
      regexp: '^#PasswordAuthentication.*$',
      replace: 'PasswordAuthentication yes'
    }
  notify: restart sshd

  #- name: Get updated rollUpIt.git
  #  git:
  #    repo: https://github.com/{{ githubuser | urlencode }}/rollUpIt.lnx
  #    version: develop
  #    dest: "{{ rollUpIt_lnx_dst }}"
  
- name: Prepare script dir
  file:
    path: "{{ rollUpIt_lnx_dst }}"
    state: directory
    owner: root
    group: develop
    mode: '0775'

- name: Copy from FTP
  shell: 'wget -r -nH --cut-dir 1 ftp://ftp_user:SUPER@172.17.0.132/pub/rollUpIt.lnx;
          chown -Rf root:develop {{ rollUpIt_lnx_dst }}/rollUpIt.lnx;
          find {{ rollUpIt_lnx_dst }}/rollUpIt.lnx -iname "*.sh" -exec chmod 755 {} \;'
  args:
    chdir: "{{ rollUpIt_lnx_dst }}"
    #- name: Copy rollUpIt.lnx
    #  copy:
    #    src: "files/rollUpIt.lnx"
    #    dest: "{{ rollUpIt_lnx_dst }}"
    #    owner: root
    #    group: develop
    #    mode: 775

- name: Get updated dotfiles (develop branch)
  git:
    repo: https://github.com/{{ githubuser | urlencode }}/dotfiles
    version: develop
    dest: /home/{{ admin_user }}/.dotfiles

- name: Basic setup
  shell: '{{ rollUpIt_lnx_dst }}/rollUpIt.lnx/tests/base/test_ansibleBasicSetup.sh {{ admin_user }}'
  register: basicSetupOutput_Reg

- debug: var=basicSetupOutput_Reg
